name: AllRisX
description: InsureTech enabled.
paginate: 10
baseurl: ''

# Build settings
# categories for tag creating
# 21 May 2018 basically categories is main menu group
permalink: /:categories/:title
excerpt_separator: <!--more-->
 
# Making navigation group separate from posts
collections:  
  products:
    output: true
    permalink: /products/:title/  
  features:
    output: true
    permalink: /features/:title/
  technologies:
    output: true
    permalink: /technologies/:title/

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
    
excluded:
  - changelog.md
  - features-slider.html
  - LICENSE.txt
  - README.md
  - README.txt
  - _plugins

sass:
  sass_dir: /assets/sass
  style: compressed